### ISSUE TITLE
Oxidize Berlin Visual Identity

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#17]
Background:

Ferrous Systems (newly founded Rust Company) would like to run a Rust conference centered around embedded systems. It should hold the standards of a FOSS conference (accessible, fair, affordable, centered around teaching and not too vendor-focused. 

The name would be Oxidize and happen in Berlin during April/May 2019.

**Comment by elioqoshi** [comment]
Notes from a past meeting:
```
Mission: Advocate for Rust in Embedded Systems as something doable and position Ferris into the scene.

Audience: Rustaceans and Embedded / Embedded Programmers (Old School Engineering Type though potentially early adopters)

Timeline: 

Conference for April - May 2019.

22nd November - Lightweight Landing Page for RustFest Rome

---------------

Directions:

Combination between Circuits and Chemistry Electron and Atoms.

- State of the Art
- New ,but stable
- Yes it's new and has new opportunites, but in a way that is reasonable and with a balance of convenience and going fast at the same time
- Usable, secure out of the box
- Ready to go
- More Product Launch feeling than vision (no Ted Talk).
- Open Collaboration
- bringing open source values to Embedded
- striving for interoperability 
- making licensing more open and easier to deal with in the ecosystem
```

**Comment by elioqoshi** [comment]
![image pasted at 2018-11-8 10-19](https://user-images.githubusercontent.com/5436686/48858530-eb785800-edbb-11e8-8c8b-4209e5948331.png)

Survey Results regarding the Brand Positioning to help us shape the direction

**Comment by ergish** [comment]
The first draft: Presentation of three logo options for Oxidize, each with a pattern and three color palettes.
https://presentator.ura.design/sq-al/4XMxYPgg?v=0&s=1&m=preview

**Comment by ergish** [comment]
Please, turn on the "Fit to Screen" option in the right corner of the top menu for a better view. Also, to check the other presentations check the top menu. The fonts are not included, so we can focus on the logo and the colors for now.

Our opinion:
The first logo option would be a better choice for many reasons.
It is simple, flexible, easy to use, recognizable and because of it's components, a better fit for Oxidize. On the other hand the second option is much more flexible and easy to use but comparing to the other options, the programming brackets are general and not a specified characteristic of Oxidize. Meanwhile the third logo option is a bit more abstract and not as simple as the first two but it fits with your first requirements.

The best way for feedback would be to comment on the artboards in the link.

Thank You!

**Comment by jamesmunns** [comment]
I think we are in agreement that we like the first option the best, @skade, please feel free to add any more details if you would like.

I personally really like the background (using the "Technology waves"), and overall we like the "pink and blue", and the "blue and green" color options.

**Comment by ergish** [comment]
Thank You James! I got your comments on the Presentator. That's very helpful.
Also, please feel free to add comments about your ideas or changes that you might recommend, if there are any.

**Comment by elioqoshi** [comment]
Thanks @jamesmunns 

We plan to refine this proposal with potentially some slight alternations on font, layout and color variation to pin down the right balance. Afterward we should be good to go to expand the design language so the visuals can be translated well into any deliverable required for the conference.

**Comment by ergish** [comment]
**An updated presentation of the Visual Identity.**
[Visual Identity.pdf](https://github.com/uracreative/works/files/2765041/Visual.Identity.pdf)

This is open to changes so please, feel free to give your feedback.

**Comment by jamesmunns** [comment]
Hey, I'm going to start collecting the items/assets we need here, and try to group them in a reasonable order.

## Must Have

- [ ] Badge Design
    - [ ] Speakers
    - [ ] Organizers
    - [ ] Attendees
- [ ] Stickers
- [ ] Slide Show Template (for day-of-conference)
- [ ] Poster Design (for venue), A4ish size
- [ ] Social Media images
    - Something for advertising posts before the venue

## Probably Need

- [ ] Standing Banner Design (for the venue, some for signs, maybe one showing sponsors) 

## Maybe need

- [ ] T Shirt Design (we are not sure if we will have T-Shirts yet)

**Comment by skade** [comment]
We're not sure about taping the talks yet, but that might add a video coverimage (is that what they are called) to that. Otherwise, the list is great, the attendee t-shirt I would put this really low-prio.

**Comment by elioqoshi** [comment]
@skade thanks for the notice. Maybe consider doing socks this year? :D

**Comment by elioqoshi** [comment]
@ergish Could you update us on this progress?

**Comment by skade** [comment]
@elioqoshi same thing, I like socks, but some people might not wear them :). I really hate textile waste. I could imagine selling them, though! Maybe a shirt and socks kit.

**Comment by ergish** [comment]
Hi guys, please check out this folder and let me know if you require any changes. Else, you can check the boxes of the list above.
[Visual Identity Assets - Delivery1.zip](https://github.com/uracreative/works/files/2841220/Visual.Identity.Assets.-.Delivery1.zip)

Also, I would need the text and the sizes of these Assets:
- Slide Show Template
- Social Media Images
- Standing Banners
- Posters (The example in the zip folder has general information)

**Comment by ergish** [comment]
@skade That's sad. I was just starting to work on those socks. :)

**Comment by elioqoshi** [comment]
>   Social Media Images

The sizes are pretty standard, but it would be useful to know what images exactly would be needed, e.g:

- Facebook Page Cover
- Facebook Event Cover
- Profile Photo
- Twitter Cover
- Mastodon Cover

If we know these, we should know the sizes.

**Comment by ergish** [comment]
Yeah, the size was more about the Slide Show. So we'll need the content (the images and the text for each post that we will design).
Twitter is set. Will OxidizeConf be on Facebook too?

**Comment by jamesmunns** [comment]
@ergish I don't plan on having a facebook or mastodon presence.

General feedback from the zip you've provided:

1. I like the badge 1 style more, but I really like the wave pattern background from badge 2. Could you please add the background to badge 1, then LGTM!
2. I'm not a big fan of either shirt design, though I like the way shirt 1 fills up the whole front. Do you have any other design ideas, but maybe still in the "whole shirt" style?
3. Impolitely, sticker design number 1 reminds me a little of "goatse", we might want to skip that one.
4. I like sticker design number 2 a lot! It would be interesting to see it in other colors or gradients, or maybe even with the wave pattern background for a two-tone sticker?
5. Of stickers 4, 5, and 6 (round stickers), I like sticker number 6 the best
6. For the posters, we would probably want a template we can use for signage around the event, more than for advertisement. I don't think we would put up physical advertising in Berlin. Could you please provide a poster design that has a "Title + Subtitle" format, we can use for directions, etc.?

I also didn't mention it above, would it be possible to get a PDF version of our [sponsors page](https://oxidizeconf.com/sponsors/packages/), with the design elements applied? This would be nice to send to potential sponsors, in addition to linking them to the website.

Thanks for getting back to us on this so quickly!

**Comment by ergish** [comment]
@jamesmunns  Hi again,
So please, check out the new zip folders:

[Visual Identity Assets - Delivery2.1.zip](https://github.com/uracreative/works/files/2852220/Visual.Identity.Assets.-.Delivery2.1.zip)
[Visual Identity Assets - Delivery2.2.zip](https://github.com/uracreative/works/files/2852222/Visual.Identity.Assets.-.Delivery2.2.zip)

1.  The badge styles now are merged in one.
2.  There are 2 t-shirt design variations added, one with the vertical logo (can be printed in white and black) and one with the design of the sticker nr.6. The previous ones are still included.
3, 4, 5. I'm sorry about that, I didn't think of it that way, but when you see it, it can't be unseen... So that version is changed. I also added some new sticker variations of nr.2 and nr.6.
6. The old vertical poster is still included as a template. I added a horizontal Slide Show Template in PDF and SVG. 

You can find the sponsors page redesigned in PDF format (included is also a version with a clickable button to send the email directly from the pdf.)

Please, if there's anything else you require, feel free to let me know about it. Even give me examples if necessary.

**Comment by jamesmunns** [comment]
1. Looks great to me!
2. I really like T-Shirt 3, the white text on black shirt!
3. The new stickers look really good!
4. I really like the sponsors PDF!

One last small request, would it be possible to get a combination of sticker 2 and sticker 8? Black sticker, with a light grey texture pattern like part8 has?

I can't think of anything else, overall looks great to me! Thank you so much @ergish!

I'll let @skade give the final sign-off, but I'm otherwise totally happy with accepting this :)

**Comment by ergish** [comment]
Thank You @jamesmunns ! 

This zip folder is the updated "8-Stickers" folder with Nr.10 added.
[8-Stickers.zip](https://github.com/uracreative/works/files/2852588/8-Stickers.zip)

**Comment by elioqoshi** [comment]
@jamesmunns Great to hear you like the deliverables :)

Please feel free in the coming weeks to let us know of any other deliverables or whether you need revisions as well.

**Comment by elioqoshi** [comment]
@jamesmunns @skade let us know when the new landing page is implemented so we can give it a review. It would be great to have the website design finished this month so March can start with a solid website presence :)

**Comment by AnXh3L0** [comment]
The visual identity for Oxidize Berlin is complete, now we're working on finalizing the website too.

**Comment by elioqoshi** [comment]
@AnXh3L0 not completely in fact. Sorry I meant to follow up here.

From what @jamesmunns  told me, we will still need:

- speaker announcement photos
- Name badges (can we somehow automate this process for doing all names @ergish ? )
- a roll-up design or two? 

@ergish Could you take this on?

**Comment by skade** [comment]
Okay, final bit: I need a couple of posters using the base design you have. Really simple ones.

1: A poster to hang by the speakers desk.
* Oxidize conference logo
* Created by Ferrous Systems
* Venue Sponsor: Thoughtworks
* Main sponsors: ARM, Decawave
* Design: Ura Creative

Please note that this will be visible in videos of the speakers desk, so it would be great if all this is a bit "Top-Heavy". Logos can be found here: https://oxidizeconf.com/

Other then that, we'd need a bit of directional signage:

* "Workshop location"
* "impl Days"
* left, right, up, down (arrows)
* If it's quickly done, the schedule https://oxidizeconf.com/schedule/.

That's it, thanks :). I can print within 24 hours, so tomorrow evening or Thursday be fine.

**Comment by ergish** [comment]
@skade hi there,

The first poster for the speakers' desk is done. 
I don't understand the second one. Should the schedule be included in one poster or do you need different posters for different locations there? How should the arrows be used?

**Comment by skade** [comment]
@ergish Ah, sorry, it's one per item. So, for each a poster:

* 1 poster with just the words "Workshop Location"
* 1 poster with just the words "impl Days"
* 4 times an arrow, in each direction
* One poster with the schedule

**Comment by skade** [comment]
@ergish sorry for this, but I forgot that "Mozilla" should be in the main sponsors on the first poster, too :).

**Comment by ergish** [comment]
@skade in the zip folder you'll find all the mentioned posters. Let me know if everything is ok or if anything else is needed.

 [Oxidize-A2 posters.zip](https://github.com/uracreative/works/files/3116837/Oxidize-A2.posters.zip)

**Comment by skade** [comment]
Perfect, thanks!

**Comment by elioqoshi** [comment]
Thanks @skade see you at the conference :)
