### ISSUE TITLE
Thunderbird Photon System in Jekyll

### ISSUE THREAD

**Issue by AnXh3L0** [uracreative/works#22]
Mozilla has lately updated their Photon Design System to Jekyll (from Node JS) and now the website works without JavaScript too.

We have to pull from the upstream and reapply the Thunderbird design language in the new Jekyll site.

**Comment by elioqoshi** [comment]
This will help have the style guide available without a backend in Jekyll and making it possible to be used with JavaScript disabled.

**Comment by elioqoshi** [comment]
This work has been approved to be performed via the OTF Usability Lab. @AnXh3L0 can you update us on the progress here?

**Comment by AnXh3L0** [comment]
Sure, I have pulled from the Firefox UX repo and reapplied the Thunderbird assets in it. Now finalizing it and trying to make it work without using Docker.

**Comment by elioqoshi** [comment]
Sounds good. It would be great to wrap that work up by tomorrow.

**Comment by AnXh3L0** [comment]
The https://github.com/uracreative/thunderbird repo now holds the design system for Thunderbird. There's still some minor changes to make as some of those don't apply to Thunderbird but only Firefox.

**Comment by elioqoshi** [comment]
@AnXh3L0 Thanks. What's the matter with GitHub pages? 

Let's make sure to add also a ReadMe to provide some context

**Comment by AnXh3L0** [comment]
@elioqoshi GitHub Pages should work now. You can see it here: https://uracreative.github.io/thunderbird/

Sure, will add some context in a README file.

**Comment by elioqoshi** [comment]
Thanks @AnXh3L0 

Some feedback to consider and I think it's good to go:

- In the Typography section, we don't need an example of line length for Mobile as Thunderbird is not available on mobile.
- I don't think there should be designsystem@thunderbird.net email. Maybe use the TopicBox UX team list should be instead there.
- Instead of the Firefox UX GitHub and Twitter, let's have the generic Thunderbird accounts there.
- On the landing page, let's ensure that it's very clear that the content is based on the Firefox Photon Design system but stripped down to suit for Thunderbird needs. Let's also link to it.
- The Thunderbird Logo is nowhere to be seen, can we include it on the landing page?

**Comment by AnXh3L0** [comment]
The changes you requested have been implemented @elioqoshi. Changes are visible from the GitHub Pages link above.

**Comment by elioqoshi** [comment]
Thanks. I think this is ready to be handed off now. cc @ryanleesipes

**Comment by ryanleesipes** [comment]
I have pinged @sancus about grabbing this.

**Comment by AnXh3L0** [comment]
I modified the README file so it reflects what has been done on the design system, closing this issue. If there's anything left or any question, feel free to open it again.
