### ISSUE TITLE
GDPR Compliance Assessment UX Review

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#24]
@giannisk asked us to help review the UX and Usability of a GDPR Assessment tool he developed. Ideally we should specify:

a) what works well
b) what doesn't work well
c) suggestions for improvement

Demo: https://dev.gdprassessment.io/

Feedback Form: https://goo.gl/forms/rzgtpKfL4NepFaXF3

(Optional Documentation) Brief Introductory Video: https://pithos.okeanos.grnet.gr/public/QVS9RyS977FAGcw7BxPZE1

**Comment by elioqoshi** [comment]
@RenataGegaj can you do a quick testing session (ideally with a tester) and do some review with recommendations from your side? I will also do a quick review by tomorrow.

Let's write the recommendations here too.

**Comment by RenataGegaj** [comment]
I conducted a testing session yesterday, I did a dry run test of the interface myself before testing with the participant. The test performed well overall! Although some small usability improvements can be made.
I tested the interface on different screens and it was responsive in every case.
There are some small details on homepage that need attention:

1. The home page needs to include more information on what GDPR Compliance is and how it works so that the new users that are not familiar with these terms(like the tester that participated on this session) can understand what the tool does before they start figuring out how to use it.


2.  The coding picture on the homepage doesn't feel relevant to the content on that section, the placement of the photo is good so it just needs to be replaced with something more relevant.
<img width="1440" alt="screenshot 2019-02-13 at 13 39 12" src="https://user-images.githubusercontent.com/7413721/52712441-dcf1a500-2f94-11e9-9ffa-7e9a21604eff.png">


3. Change the title font or font size for readability purposes(it looks like the title and subtitle are together)
<img width="1440" alt="screenshot 2019-02-13 at 13 39 26" src="https://user-images.githubusercontent.com/7413721/52712509-1c1ff600-2f95-11e9-8cf1-35cab8d1d357.png">

Documentation should feel like a guide to the user, it should look like you are talking to the user. Ex: avoid “Users should fill in the registration form and accept the terms of use and privacy policy to create their account.” with something similar to "Please fill in the registration form and accept the terms of use and privacy policy to create your account."
<img width="892" alt="screenshot 2019-02-13 at 13 44 16" src="https://user-images.githubusercontent.com/7413721/52712923-50e07d00-2f96-11e9-98ca-a6f04f9a7650.png">


Include the full sentence on the options. Ex: Yes, my organisation has implemented appropriate technical and organisational measures for...?(the screenshot couldn't capture it, click to see the options)

<img width="643" alt="screenshot 2019-02-13 at 12 44 34" src="https://user-images.githubusercontent.com/7413721/52713162-df54fe80-2f96-11e9-8cd4-bee006e896fa.png">
 
The "Begin Assessment" button on the homepage should lead to "Processing Activity" first since that is a necessary step to complete before moving to GDPR Assessment. The link on the bottom of the page leads there but is not very practical and then when you finish the processing activity the user doesn't know what to do next. You should lead the user back to GDPR Assessment.
My scenario: Clicked the "Begin Assessment" button on the homepage which lead me to GDPR Assessment and I filled it, then the error link sent me to Processing Activity and I filled that to. When I got back to GDPR Assessment all the data I filled was lost.

**Comment by elioqoshi** [comment]
Thanks @RenataGegaj ! Adding my suggestions here as well:

>     1. Change the title font or font size for readability purposes(it looks like the title and subtitle are together)

Indeed. Also, please ideally ensure that text is WCAG 2.0 compliant for accessibility purposes:
https://webaim.org/resources/contrastchecker/

In the case of the hero section, the text barely passes AA. To be AAA compliant, you should have a bigger contrast ratio with the background. This is not a huge deal considering the contrast passes, but the hero image is not really of any relevance, and mostly aesthetical, so you might consider something different, or even abstract (as photos for GDPR are quite rare and cheesy).

Unsplash has some good abstract stuff as well:
https://unsplash.com/search/photos/abstract

-----
Further, the dashboard card icons might benefit from being black (with 25% opacity or something) instead of pure white as on some resolutions it can happen that the text overrides the image:

![image](https://user-images.githubusercontent.com/5436686/52716319-cbad9600-2f9e-11e9-9a72-03f32933e0dc.png)

Regarding the top bar and the sidebar, I'd suggest to follow (and simply copy) the approach GitLab does:
![image](https://user-images.githubusercontent.com/5436686/52716481-1fb87a80-2f9f-11e9-8bce-7b5bcddb2717.png)

Check out the patterns they use regarding hover states and sizing and margins as they work really well! They are too many to list them neatly here, but I'd be happy to give another review later on as well.

One more thing for the sidebar: the collapse/expand button is not very clear. Have a look at the Atlassian Design Guidelines: https://atlassian.design/server/patterns/sidebar/

They use a double arrow instead and place it on the edge of the sidebar (not the middle).

-----

Regarding content, some more margins would be better as the content is very close to the sidebar. Currently:
![image](https://user-images.githubusercontent.com/5436686/52717214-e1bc5600-2fa0-11e9-851a-3a86f7453ed5.png)

Suggested (approximately):
![image](https://user-images.githubusercontent.com/5436686/52717245-f993da00-2fa0-11e9-90b3-9364f8350e8f.png)

Generally some more white space is good.

----

That's mostly it. If you address these I think it should be really good to go. We would be happy to design a quick logo for you as well if you like :)

**Comment by elioqoshi** [comment]
@giannisk let us know if you need further clarifications or whether that's good to go for your side :)

**Comment by elioqoshi** [comment]
Closing this as finished unless there is anything else needed.
