### ISSUE TITLE
Save by OpenArchive Logo & Branding

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#26]
https://open-archive.org/

We are helping OpenArchive with branding for their newly named "Save" app. The work will include a logo and fundamental brand guidelines.

**Comment by elioqoshi** [comment]
Brief by Natalie:

 our next step is to find a visual language that creates an intuitive framing that:
- is memorable enough that if someone has seen the icon before, they can find it amongst their other apps. 
- creating a baseline brand identity that looks sleek enough to be able to sit along other apps (eg, what does our roll-down poster look like in a few words, a logo and maybe some supplemental images that frame the tool)
- differentiate it from the floppy disk that you mentioned. this is a new way to save, and as such, we want to find a way to build on people's understanding of media management but also show that it can be more than the status quo. 
- find a color scheme
- decide on a type font that is a) easy to read, b) has bold, italic, etc options; c) hopefully have  non-Latin script equivalent

So, as an exercise to see if we are able to find alignment on branding scope now that we've clarified where we are-lets go to go back to the roll-down poster: we want people sitting half-way back in a room to be able to get an idea of the tool through visual elements before we've even gone up to present. 

As mentioned in the literature and communications I sent before: the brand for OpenArchive should communicate a safe, verifiable ecosystem that preserves digital media made my at-risk groups. For "Save", the mobile application, we also want to convey a safe/secure way to route media to a "public" or "private" trustworthy backend that will organize the media efficiently when sent to the server.

The core values of the project are:

- privacy when media is in transit
- long term access to the media (preservation / archiving)
- media authentication / verification (via proofmode and hashes/signatures, etc.)
- consent and creator's intention for what others can do with the media once it is public (at the internet archive) or private (on an internal server)

this project was made for archiving/preserving sensitive media made by at-risk groups

**Comment by ergish** [comment]
Here's a PDF document presenting five logo options for SAVE including the color palettes, the fonts, and some logo alternations. The main focus, for now, is choosing a path for the logo style and then we'll provide other revisions of that option.

[Save byOpenArchive - LogoDraft1 - Presentation.pdf](https://github.com/uracreative/works/files/2900454/Save.byOpenArchive.-.LogoDraft1.-.Presentation.pdf)

**Comment by ergish** [comment]
We received a detailed feedback on the last presentation, followed by some requests/suggestions on the concept of the logo:

* Explore the letter "S" as the shape. Particularly as it relates to the infinity sign.
* Instead of having it be an upright closed infinity symbol (which looks like an 8) perhaps break it slightly so that it's implying infinity. 
* The logo should convey the multiple layers/processes of the media ecosystem.

Draft Nr.2 is based on these suggestions:
 [Save byOpenArchive - LogoDraft2 - Presentation.pdf](https://github.com/uracreative/works/files/2930436/Save.byOpenArchive.-.LogoDraft2.-.Presentation.pdf)

**Comment by ergish** [comment]
Another updated revision:
* simplified the shapes and the colors
* added two more logo concepts

[Save byOpenArchive - LogoDraft3 - Presentation.pdf](https://github.com/uracreative/works/files/2937215/Save.byOpenArchive.-.LogoDraft3.-.Presentation.pdf)

**Comment by ergish** [comment]
Another updated revision:
* simplified the shapes and the colors
* added two more logo concepts

[Save byOpenArchive - LogoDraft3 - Presentation.pdf](https://github.com/uracreative/works/files/2937259/Save.byOpenArchive.-.LogoDraft3.-.Presentation.pdf)

**Comment by ergish** [comment]
So, I designed another version of the logo based on the client's requirements regarding the concept. Following each requirement like an instruction book would not be a good idea because obviously, there should be no conflict between what the client requests and what we agree to offer.

The first icon in the file attached would be the primary logo.

[Save byOpenArchive - LogoDraft5 - Presentation.pdf](https://github.com/uracreative/works/files/2946119/Save.byOpenArchive.-.LogoDraft5.-.Presentation.pdf)

**Comment by elioqoshi** [comment]
We delivered these proposals after 4 revisions. OpenArchive is eventually doing changes on their own as none of the proposals worked for them.
