### ISSUE TITLE
Global Leaks Redesign

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#36]
## Scope of work
Our work will help GlobaLeaks further improve its user experience by providing usability and design services in four phases:

### User research
Deliverables:
* Report and recommendations based on qualitative research
* Participants and findings will be anonymized
* Report will be shareable openly
* Report will include process and methodology, as well as findings

### Usable security review
Deliverables:
* Report and recommendations based on usable security review (shareable)
* (Optional): Accessibility review

### UX/UI design & testing
Deliverables:
* Workflows for each individual group of users
* UI wireframes

### Visual design
Deliverables:
* Interactive UI prototypes
* UI mockups ready for development
* Style guide (web-based in Jekyll)

**Comment by RenataGegaj** [comment]
We successfully completed the first two phases of the project!
* During the research phase, we conducted 8 interviews in total. Four recipient/admins, One admin Only and three potential whistleblowers. We interviewed people from Europe, Asia, and the US. Four of them were NGO and one corporate.

* We analyzed the results with the internal team and shared two reports, one for our research findings and the other with recommendations for improvements.

* We also conducted a heuristic evaluation of the admin interface, recipient interface, and whistleblowers interface. We documented the report and shared it.

**Comment by RenataGegaj** [comment]
As we are wrapping up the design phase, here are some updates on the progress so far:

- We started the redesign with an information architecture exercise. We gathered/analyzed the results  and used them to guide the layout 
- Incorporated role-based access control on admin interface
- Created Low Fidelity sketches/wireframes for admin, recipient, and whistleblower interfaces
- Conducted three sessions of semi-structured user interviews and comparative usability testing 
- Iterated based on the gathered feedback
- Transformed the low fidelity wireframes to high fidelity mockups

**Comment by elioqoshi** [comment]
First HiFi Prototype of the Home screen here:
https://www.figma.com/proto/OW4Xl74VlJIQu4GssFK9gX/GlobaLeaks-Design-System?node-id=50%3A826&viewport=557%2C247%2C0.39300379157066345&scaling=min-zoom

(toggle dashboard is interactive)

**Comment by elioqoshi** [comment]
We should probably create more issues in the future for such big projects :)

The Brand Guidelines are done: 
https://send.firefox.com/download/3d4af62bb72a7c61/#bhAXZCMbn_AwDTgN8jttsA

There are some changes needed though, mostly these: 

1. Use the Primary Blue instead of the dark blue on the first page
2. Change the pattern to the new logo on the background in the first page (2 people whispering)
3. Change the dark blue line on top of the guidelines to primary blue (to make it clear that primary blue is well… primary)
4. Change last page to primary blue


We will move forward with the remaining mockups now.

**Comment by elioqoshi** [comment]
@teolf It seems that the colors used in the brand guideliens are different from the Hexcode. Is this maybe due to some CMYK conversion in the PDF?

If you check it here you can notice a slight difference between the color showed and the hexcode color:
<img width="726" alt="grafik" src="https://user-images.githubusercontent.com/5436686/78693358-6a135e00-78fb-11ea-8ba4-07cea673657d.png">

<img width="931" alt="grafik" src="https://user-images.githubusercontent.com/5436686/78693386-739cc600-78fb-11ea-8a47-7ce09da64d71.png">

**Comment by teolf** [comment]
@elioqoshi I fixed the issues addressed above. The colors were affected by RGB to CMYK conversion.

Here is the updated file:
https://send.firefox.com/download/dd7d5fa3bf5bcfd6/#a-6Llb_WMax9L9DbDHQ2lw

**Comment by elioqoshi** [comment]
@teolf Thanks!

Seems that link expired, here is the updated one:
https://send.firefox.com/download/1869e69cdff8785d/#OPS9knUnnuhZlv1FL6xb6g
