### ISSUE TITLE
Visual Design exploration & reviews

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#65]
This is phase 3 of the project, including:
- Visual design language explorations
- Stakeholder reviews + Iterations
- Brand guidelines

**Comment by ergishkelzeni** [comment]
Hi everyone,

Updating the status of Totem's visual re-design phase:

We shared some proposals regarding the visual brand. These proposals aim to improve the accessibility of the website while setting a new visual identity and a UX system for Totem Project. These include:

**1. A proposal regarding the color system and typography, followed by web mockups to create an idea of their implementation.**


Having a color system would help in improving the user experience by offering the right color combination in each case so that accessibility is never compromised. Here's a color system with 11 shades of Green Emerald and 2 shades of Gray, (50 would be too much). The diversity of shades helps in having a more defined visual identity, setting the floor for future illustrations, icons, and other graphic elements. These colors seem to give a new fresh feeling to Totem Project.

Regarding the fonts, we would like to replace Ubuntu with Maven Pro, while Noto Sans remains as a secondary font for body text. Maven Pro seems to resemble Ubuntu a lot, while it has a more unique character. This replacement also withdraws you from using a font that represents another well-known project.

![New Color System and Typography](https://user-images.githubusercontent.com/55448475/144279375-c787e37f-3fea-4796-86f3-682b00ac441b.png)

The image below illustrates the current state of the website (https://totem-project.org/)

![Current](https://user-images.githubusercontent.com/55448475/144279419-4f2e74e3-08b9-4e39-a706-a1361f524ecc.png)

Here you can see the implementation of the new colors and the fonts. What's important in all we are offering is to improve the accessibility. For better readability, we should use the required contrast for Web Accessibility (Level AA). Also, the text alignment and the spacing need to change for a better experience. 
These mockups below have only one difference, the dark/light header. The light one is our favorite. :)

![Mockup 1 Dark Header](https://user-images.githubusercontent.com/55448475/144279426-1f89da98-dabb-4b68-b5b3-54378a145505.png)
![Mockup 2 Light Header](https://user-images.githubusercontent.com/55448475/144279441-bc9c951b-7fac-4b77-a348-527e167f1b58.png)

Please, feel free to give your feedback here in the comments!

**Comment by elioqoshi** [comment]
@tingeber At which point do you think we can proceed with the logo direction feedback?

**Comment by ergishkelzeni** [comment]
Hi @tingeber, 

Just wondering if there's any update on deciding whether to keep the current logo or go with one of the proposed directions. Some feedback from your side would be appreciated so we know what you think would be best for Totem's brand identity, which would help us proceed with the preparation of the brand assets and the brand book.

**Comment by ergishkelzeni** [comment]
Hello @tingeber 

We were thinking of delivering the visual assets we produced, without considering the new logos. Considering the fact that we wanted to propose new logos as a bonus with the new visual look, not being a main focus of the project, we are proceeding with this logo (below) which is slightly different from the one you currently use.
<br>
<img src="https://user-images.githubusercontent.com/55448475/147000547-95659d0a-4f42-439a-b1c6-49b53a3bfe09.png" width="300">
<br>
The font is changed to match the rounded graphics of the brand and the colors of the icon now come from the new Emerald color palette.

If you want to consider a re-brand with a new logo as the main focus, we can discuss that separately outside of this engagement.

**Comment by elioqoshi** [comment]
Guidelines are prepared in: https://github.com/uracreative/works/issues/70
