### ISSUE TITLE
Website wireframes

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#92]

**Comment by rudolfburgaj** [comment]
The website wireframe can be accessed from the link below:
https://www.figma.com/file/fJrY1fUhvkwPVTrYn9y5Hd/UI?node-id=399%3A4350

**Comment by tingeber** [comment]
The wireframes are looking great @rudolfburgaj ! I'll leave my comments here, so I have more space to write.



### General
Overall, we are very much on the right track. The look and feel is just right; it is consistent and visually pleasing, presents information simply, flows well. Some general reflections and questions:
- Can you tell me more about graphical elements? I am assuming they act both as placeholders for screenshots, as well as quality "fallback" elements we can use in places we either don't want a screenshot, or don't have one ready yet
- Apart from the main page, we will also need a layout for a blog roll (for the news), a single article view, and a generic page (for the Values page).

### Top Menu
- Please change to `Menu | News | Why Stackspin? | Documentation`
- Replace `sign in | sign up` with the CTA
- Will the top menu change when scrolling? Does it stay fixed?

### Hero
- Looking very good, the more I look at it, the more I like the choice of tagline.
- There's new content for the second sentence in the content document
- Tell me more about the illustration please


### Testimonials
- We won't have them for awhile, but I also don't want to remove the element because it would make the visual alternation more complicated once we bring it back. So for now I suggest to put user groups in there -- I added some text in the hedgedoc, please check it out. 
- Ideally we'd want an icon representing each user group

### Benefits
- I see where you're going with it, but I need to be convinced that hiding content behind user interaction is worth it.
- We need to talk about user interaction. How do the section slide on mouse slide? do users need to intentionally scroll the titles, or would it be part of the overall page scrollytelling action? I am cautious about each approach, one requires people to actively engage, the other interrupts an expected behavior. I don't mind taking lots of space with the benefits, scrolling is the easiest thing.

### Features
- Great idea in splitting custom (dashboard) from apps. i realize I need to give you much more info there, so let's please talk about what exactly would be useful there.

### Why?
- Spot on
- The link here should take people to the "why" page instead of being a CTA. Or, we should have both, But I'm assuming that, if the users got this far, they will want to keep reading about us.

### Footer
- looks great.

**Comment by rudolfburgaj** [comment]
Thank you @tingeber for the detailed feedback!

### General
* Yes the graphical elements are serving as a placeholder for now. It might be a potential illustration style to develop as well.

### Top Menu
* When you scroll down the top menu can hide, and only show when the user scrolls up. 

### Hero
* The illustration in the hero section, again serves as a placeholder, but it can be developed more.

### Benefits
* The way I was thinking to work is that the sections will scroll while the user scrolls down. Initially, I thought to preserve some space but making the website a bit longer doesn't hurt I guess. So for this section, I will present another approach.

### Features
* I would say if you provide a couple of words to describe each point would suffice here.

### Why
* I suggest we keep them both: "Why Staskspin", "Get Stackspin"

Again thanks for the detailed feedback, and next I will tackle all the points you mentioned and come with a second draft.

**Comment by elioqoshi** [comment]
@rudolfburgaj since this went into the mockup stage, this can be closed, right?

**Comment by rudolfburgaj** [comment]
Yes, that's correct. Closing it now!

**Comment by rudolfburgaj** [comment]
> Yes, that's correct. Closing it now!

Already closed. Great!
